import 'package:flutter/material.dart';
import '../../core/constants/colors.dart';
import '../../core/constants/spacing.dart';
import '../../core/di/service_locator.dart';
import '../../models/shop_monthly_report.dart';
import '../../services/shop_service.dart';
import '../../widgets/common/app_card.dart';
import '../../widgets/common/loading_indicator.dart';

/// Monthly performance report screen for shop owners.
///
/// Data is read-only, generated by Cloud Functions at the start of each month.
class ShopMonthlyReportScreen extends StatefulWidget {
  final String shopId;

  const ShopMonthlyReportScreen({super.key, required this.shopId});

  @override
  State<ShopMonthlyReportScreen> createState() =>
      _ShopMonthlyReportScreenState();
}

class _ShopMonthlyReportScreenState extends State<ShopMonthlyReportScreen> {
  ShopMonthlyReport? _report;
  bool _isLoading = true;
  String? _error;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });
    final result = await sl.get<ShopService>().getMonthlyReport(widget.shopId);
    if (!mounted) return;
    result.when(
      success: (report) => setState(() {
        _report = report;
        _isLoading = false;
      }),
      failure: (err) => setState(() {
        _error = err.userMessage;
        _isLoading = false;
      }),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('月次レポート')),
      body: _isLoading
          ? const AppLoadingCenter(message: '読み込み中...')
          : _error != null
              ? AppErrorState(message: _error!, onRetry: _load)
              : _report == null
                  ? _NoReportState(onRetry: _load)
                  : _ReportBody(report: _report!),
    );
  }
}

// ---------------------------------------------------------------------------
// No report yet state
// ---------------------------------------------------------------------------

class _NoReportState extends StatelessWidget {
  final VoidCallback onRetry;

  const _NoReportState({required this.onRetry});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Center(
      child: Padding(
        padding: AppSpacing.paddingScreen,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.bar_chart_outlined,
              size: 64,
              color: theme.colorScheme.outline,
            ),
            AppSpacing.verticalMd,
            Text(
              'まだレポートがありません',
              style: theme.textTheme.titleMedium,
              textAlign: TextAlign.center,
            ),
            AppSpacing.verticalXs,
            Text(
              '月次レポートは毎月1日にCloud Functionsにより自動生成されます。\n'
              '掲載後の翌月以降に最初のレポートが届きます。',
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.onSurfaceVariant,
              ),
              textAlign: TextAlign.center,
            ),
            AppSpacing.verticalLg,
            OutlinedButton.icon(
              onPressed: onRetry,
              icon: const Icon(Icons.refresh),
              label: const Text('再読み込み'),
            ),
          ],
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Report body
// ---------------------------------------------------------------------------

class _ReportBody extends StatelessWidget {
  final ShopMonthlyReport report;

  const _ReportBody({required this.report});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return SingleChildScrollView(
      padding: AppSpacing.paddingScreen,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Month header
          Row(
            children: [
              const Icon(Icons.calendar_month_outlined,
                  color: AppColors.primary),
              AppSpacing.horizontalSm,
              Text(
                '${report.month} のパフォーマンス',
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          AppSpacing.verticalSm,
          Text(
            '更新: ${_formatDate(report.updatedAt)}',
            style: theme.textTheme.labelSmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
          AppSpacing.verticalLg,

          // Inquiry section
          _SectionHeader(title: '問い合わせ', icon: Icons.mail_outline),
          AppSpacing.verticalSm,
          AppCard(
            child: Column(
              children: [
                _MetricRow(
                  label: '累計問い合わせ',
                  value: '${report.totalInquiries} 件',
                  valueColor:
                      report.totalInquiries > 0 ? AppColors.primary : null,
                ),
                const Divider(height: AppSpacing.md),
                _MetricRow(
                  label: '新規（今月）',
                  value: '${report.newInquiries} 件',
                  valueColor:
                      report.newInquiries > 0 ? AppColors.success : null,
                ),
                const Divider(height: AppSpacing.md),
                _MetricRow(
                  label: '対応完了',
                  value: '${report.resolvedInquiries} 件',
                ),
              ],
            ),
          ),
          AppSpacing.verticalMd,

          // Visibility section
          _SectionHeader(title: '露出・閲覧', icon: Icons.visibility_outlined),
          AppSpacing.verticalSm,
          AppCard(
            child: Column(
              children: [
                _MetricRow(
                  label: '店舗ページ閲覧数',
                  value: '${report.pageViews} 回',
                  valueColor: report.pageViews > 0 ? AppColors.info : null,
                ),
                const Divider(height: AppSpacing.md),
                _MetricRow(
                  label: '検索結果表示回数',
                  value: '${report.searchAppearances} 回',
                ),
              ],
            ),
          ),
          AppSpacing.verticalXl,

          // Note
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(
                Icons.info_outline,
                size: AppSpacing.iconSm,
                color: theme.colorScheme.onSurfaceVariant,
              ),
              AppSpacing.horizontalXs,
              Expanded(
                child: Text(
                  'データはCloud Functionsにより自動集計されます。'
                  '最新のデータは翌月1日以降に反映されます。',
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ),
              ),
            ],
          ),
          AppSpacing.verticalLg,
        ],
      ),
    );
  }

  String _formatDate(DateTime dt) =>
      '${dt.year}/${dt.month.toString().padLeft(2, '0')}/${dt.day.toString().padLeft(2, '0')}';
}

class _SectionHeader extends StatelessWidget {
  final String title;
  final IconData icon;

  const _SectionHeader({required this.title, required this.icon});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Icon(icon, size: AppSpacing.iconSm, color: AppColors.primary),
        AppSpacing.horizontalXs,
        Text(
          title,
          style: Theme.of(context).textTheme.labelMedium?.copyWith(
                color: Theme.of(context).colorScheme.onSurfaceVariant,
                fontWeight: FontWeight.bold,
              ),
        ),
      ],
    );
  }
}

class _MetricRow extends StatelessWidget {
  final String label;
  final String value;
  final Color? valueColor;

  const _MetricRow({
    required this.label,
    required this.value,
    this.valueColor,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: AppSpacing.xs),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: theme.textTheme.bodyMedium),
          Text(
            value,
            style: theme.textTheme.titleSmall?.copyWith(
              fontWeight: FontWeight.bold,
              color: valueColor,
            ),
          ),
        ],
      ),
    );
  }
}
