// Mocks generated by Mockito 5.x from annotations
// in trust_car_platform/test/services/ai_chat_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

import 'dart:async' as _i4;
import 'dart:convert';

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ---------------------------------------------------------------------------
// MockClient
// ---------------------------------------------------------------------------

/// A class which mocks [http.Client].
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#head, [url], {#headers: headers}),
        returnValue: _i4.Future<_i3.Response>.value(_i3.Response('', 200)),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<_i3.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#get, [url], {#headers: headers}),
        returnValue: _i4.Future<_i3.Response>.value(_i3.Response('', 200)),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i4.Future<_i3.Response>.value(_i3.Response('', 200)),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i4.Future<_i3.Response>.value(_i3.Response('', 200)),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i4.Future<_i3.Response>.value(_i3.Response('', 200)),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
        returnValue: _i4.Future<_i3.Response>.value(_i3.Response('', 200)),
      ) as _i4.Future<_i3.Response>);

  @override
  _i4.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#read, [url], {#headers: headers}),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<int>> readBytes(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#readBytes, [url], {#headers: headers}),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  _i4.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(#send, [request]),
        returnValue: _i4.Future<_i3.StreamedResponse>.value(
          _i3.StreamedResponse(const Stream.empty(), 200),
        ),
      ) as _i4.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(#close, []),
        returnValueForMissingStub: null,
      );
}

// ---------------------------------------------------------------------------
// MockFirebaseAuth
// ---------------------------------------------------------------------------

/// A class which mocks [FirebaseAuth].
class MockFirebaseAuth extends _i1.Mock implements _i2.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User? get currentUser => (super.noSuchMethod(
        Invocation.getter(#currentUser),
        returnValueForMissingStub: null,
      ) as _i2.User?);

  @override
  Stream<_i2.User?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(#authStateChanges, []),
        returnValue: Stream<_i2.User?>.empty(),
      ) as Stream<_i2.User?>);

  @override
  Stream<_i2.User?> idTokenChanges() => (super.noSuchMethod(
        Invocation.method(#idTokenChanges, []),
        returnValue: Stream<_i2.User?>.empty(),
      ) as Stream<_i2.User?>);

  @override
  Stream<_i2.User?> userChanges() => (super.noSuchMethod(
        Invocation.method(#userChanges, []),
        returnValue: Stream<_i2.User?>.empty(),
      ) as Stream<_i2.User?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(#signOut, []),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

// ---------------------------------------------------------------------------
// MockUser
// ---------------------------------------------------------------------------

/// A class which mocks [User].
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: 'mock-uid',
      ) as String);

  @override
  String? get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  String? get displayName => (super.noSuchMethod(
        Invocation.getter(#displayName),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  String? get photoURL => (super.noSuchMethod(
        Invocation.getter(#photoURL),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  bool get emailVerified => (super.noSuchMethod(
        Invocation.getter(#emailVerified),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<String?> getIdToken([bool? forceRefresh]) =>
      (super.noSuchMethod(
        Invocation.method(#getIdToken, [forceRefresh]),
        returnValue: _i4.Future<String?>.value('mock-id-token'),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(#reload, []),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(#delete, []),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmailVerification([
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(#sendEmailVerification, [actionCodeSettings]),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i2.UserInfo> get providerData => (super.noSuchMethod(
        Invocation.getter(#providerData),
        returnValue: <_i2.UserInfo>[],
      ) as List<_i2.UserInfo>);

  @override
  String? get phoneNumber => (super.noSuchMethod(
        Invocation.getter(#phoneNumber),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  String? get tenantId => (super.noSuchMethod(
        Invocation.getter(#tenantId),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  _i4.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {#displayName: displayName, #photoURL: photoURL},
        ),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(#updateDisplayName, [displayName]),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
        Invocation.method(#updatePhotoURL, [photoURL]),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(#updateEmail, [newEmail]),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(#updatePassword, [newPassword]),
        returnValue: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
