import 'package:cloud_firestore/cloud_firestore.dart';

/// Monthly performance report for a shop, generated by Cloud Functions.
///
/// Document path: shop_monthly_reports/{shopId}
/// The document always reflects the most recently completed month.
class ShopMonthlyReport {
  final String shopId;
  final String month; // "YYYY-MM"
  final int totalInquiries;
  final int newInquiries;
  final int resolvedInquiries;
  final int pageViews;
  final int searchAppearances;
  final DateTime updatedAt;

  const ShopMonthlyReport({
    required this.shopId,
    required this.month,
    required this.totalInquiries,
    required this.newInquiries,
    required this.resolvedInquiries,
    required this.pageViews,
    required this.searchAppearances,
    required this.updatedAt,
  });

  factory ShopMonthlyReport.fromFirestore(
      DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data()!;
    return ShopMonthlyReport(
      shopId: doc.id,
      month: (data['month'] as String?) ?? '',
      totalInquiries: (data['totalInquiries'] as num?)?.toInt() ?? 0,
      newInquiries: (data['newInquiries'] as num?)?.toInt() ?? 0,
      resolvedInquiries: (data['resolvedInquiries'] as num?)?.toInt() ?? 0,
      pageViews: (data['pageViews'] as num?)?.toInt() ?? 0,
      searchAppearances: (data['searchAppearances'] as num?)?.toInt() ?? 0,
      updatedAt: (data['updatedAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toMap() => {
        'shopId': shopId,
        'month': month,
        'totalInquiries': totalInquiries,
        'newInquiries': newInquiries,
        'resolvedInquiries': resolvedInquiries,
        'pageViews': pageViews,
        'searchAppearances': searchAppearances,
        'updatedAt': Timestamp.fromDate(updatedAt),
      };
}
