// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQ4UK6IXiUKNJ3u1Cjup4nIEmiV97O0Q',
    appId: '1:31421119456:web:b4cb461b8951f19e80c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    authDomain: 'trust-car-platform.firebaseapp.com',
    storageBucket: 'trust-car-platform.firebasestorage.app',
    measurementId: 'G-ZFX8W1PF0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZQ4UK6IXiUKNJ3u1Cjup4nIEmiV97O0Q',
    appId: '1:31421119456:android:cc5714538a154c3f80c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    storageBucket: 'trust-car-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQ4UK6IXiUKNJ3u1Cjup4nIEmiV97O0Q',
    appId: '1:31421119456:ios:4320af5d1401f02c80c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    storageBucket: 'trust-car-platform.firebasestorage.app',
    iosBundleId: 'com.example.trustCarPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZQ4UK6IXiUKNJ3u1Cjup4nIEmiV97O0Q',
    appId: '1:31421119456:ios:4320af5d1401f02c80c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    storageBucket: 'trust-car-platform.firebasestorage.app',
    iosBundleId: 'com.example.trustCarPlatform',
  );
}
