// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQ4UK6IXiUKNJ3u1Cjup4nIEmiV97O0Q',
    appId: '1:31421119456:web:b4cb461b8951f19e80c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    authDomain: 'trust-car-platform.firebaseapp.com',
    storageBucket: 'trust-car-platform.firebasestorage.app',
    measurementId: 'G-ZFX8W1PF0N',
  );

  // 2026-08-23: applicationId は jp.trustcar.app なのに、ここは
  // com.example.trust_car_platform 用のアプリを指していた（apiKey も web の
  // ものが入っていた）。jp.trustcar.app の Android アプリを Firebase に
  // 新規登録し、その値に差し替えた。
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjPzpdQqXFl4be7oE3n-yzcl6hoLv_Uw',
    appId: '1:31421119456:android:145b8b79b1d9e7cf80c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    storageBucket: 'trust-car-platform.firebasestorage.app',
  );

  // 2026-08-25: Firebase の iOS アプリを jp.trustcar.app で新規登録し直した。
  // それまでは com.example.trustCarPlatform のアプリID に iosBundleId だけ
  // jp.trustcar.app と書いた**実在しない組み合わせ**で、iOS は白画面のまま
  // 起動しなかった。apiKey も web のもの（AIzaSyDZQ4UK6I…）が入っていた。
  // 2026-08-23 に Android で直したのと同じ形。
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0hMKqo9viDFCXvNcDpNWcQ34seKfPEg',
    appId: '1:31421119456:ios:5646ac324f34398880c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    storageBucket: 'trust-car-platform.firebasestorage.app',
    iosBundleId: 'jp.trustcar.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0hMKqo9viDFCXvNcDpNWcQ34seKfPEg',
    appId: '1:31421119456:ios:5646ac324f34398880c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    storageBucket: 'trust-car-platform.firebasestorage.app',
    iosBundleId: 'jp.trustcar.app',
  );
}
