// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A platform-specific options object that contains the set of settings for
/// initializing FlutterFire on a given platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Web configuration
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQ4UK6IXiUKNJ3u1Cjup4nIEmiV97O0Q',
    appId: '1:31421119456:web:b4cb461b8951f19e80c985',
    messagingSenderId: '31421119456',
    projectId: 'trust-car-platform',
    authDomain: 'trust-car-platform.firebaseapp.com',
    storageBucket: 'trust-car-platform.firebasestorage.app',
    measurementId: 'G-ZFX8W1PF0N',
  );
}
